#:kivy 1.0.9
<ScreenManagement>:
    StartScreen:
        id:page1

    ListyZakupow:
        id:page2

    MojaLodowa:
        id:page3

    Przepisy:
        id:page4    
    

<StartScreen>:
    name:'menu'
    
    GridLayout:
        cols: 3
        rows: 1
        row_force_default: True
        row_default_height: 70
        
        Button:
            text: 'Listy zakupów'
            on_press: root.manager.current = 'ListyZakupow'

        Button:
            text: 'Moja Lodówa'
            on_press: root.manager.current = 'MojaLodowa'

        Button:
            text: 'Przepisy'
            on_press: root.manager.current = 'Przepisy'

<ListyZakupow>:
    name: 'ListyZakupow'

    GridLayout:
        cols: 3
        rows: 1
        row_force_default: True
        row_default_height: 70
        
        
        Button:
            text: 'Listy zakupów'
            background_color: (0,1,0,1)
            on_press: root.manager.current = 'ListyZakupow'

        Button:
            text: 'Moja Lodówa'
            on_press: root.manager.current = 'MojaLodowa'
        Button:
            text: 'Przepisy'
            on_press: root.manager.current = 'Przepisy'

<MojaLodowa>:
    name: 'MojaLodowa'

    GridLayout:
        cols: 1
        rows: 2
        row_force_default: True
        row_default_height: 70
        
        GridLayout:
            cols: 3
            rows: 1
            Button:
                text: 'Listy zakupów'
                on_press: root.manager.current = 'ListyZakupow'

            Button:
                text: 'Moja Lodówa'
                background_color: (0,1,0,1)
                on_press: root.manager.current = 'MojaLodowa'

            Button:
                text: 'Przepisy'
                on_press: root.manager.current = 'Przepisy'

        ScrollView:
            size: self.size
            GridLayout:
                cols: 1
                row_default_height: '20dp'
                row_force_default: True
                spacing: 0,0
                padding: 0,0

                Label:
                    text: 'Test'

<Przepisy>:
    name: 'Przepisy'

    GridLayout:
        cols: 3
        rows: 1
        row_force_default: True
        row_default_height: 70
        
        Button:
            text: 'Listy zakupów'
            on_press: root.manager.current = 'ListyZakupow'

        Button:
            text: 'Moja Lodówa'
            on_press: root.manager.current = 'MojaLodowa'

        Button:
            text: 'Przepisy'
            background_color: (0,1,0,1)
            on_press: root.manager.current = 'Przepisy'