#:kivy 1.0.9
<RV_Lodowa>:
    viewclass: 'Label'
    orientation: 'vertical'
    spacing: 10
    padding: 10, 10
    space_x: self.size[0]/3

    RecycleBoxLayout:
        color: (0, 0.7, 0.4, 0.8)
        default_size: None, dp(56)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: "vertical"

<RV_Lista>:
    viewclass: 'Label'
    orientation: 'vertical'
    spacing: 10
    padding: 10, 10
    space_x: self.size[0]/3

    RecycleBoxLayout:
        color: (0, 0.7, 0.4, 0.8)
        default_size: None, dp(56)
        default_size_hint: 0.4, None
        size_hint_y: None
        height: self.minimum_height
        orientation: "vertical"

<RV_Sniadanie>:
    viewclass: 'Label'
    orientation: 'vertical'
    spacing: 10
    padding: 10, 10
    space_x: self.size[0]/3

    RecycleBoxLayout:
        color: (0, 0.7, 0.4, 0.8)
        default_size: None, dp(56)
        default_size_hint: 0.4, None
        size_hint_y: None
        height: self.minimum_height
        orientation: "vertical"

<RV_Lunch>:
    viewclass: 'Label'
    orientation: 'vertical'
    spacing: 10
    padding: 10, 10
    space_x: self.size[0]/3

    RecycleBoxLayout:
        color: (0, 0.7, 0.4, 0.8)
        default_size: None, dp(56)
        default_size_hint: 0.4, None
        size_hint_y: None
        height: self.minimum_height
        orientation: "vertical"

<RV_Obiad>:
    viewclass: 'Label'
    orientation: 'vertical'
    spacing: 10
    padding: 10, 10
    space_x: self.size[0]/3

    RecycleBoxLayout:
        color: (0, 0.7, 0.4, 0.8)
        default_size: None, dp(56)
        default_size_hint: 0.4, None
        size_hint_y: None
        height: self.minimum_height
        orientation: "vertical"

<RV_Kolacja>:
    viewclass: 'Label'
    orientation: 'vertical'
    spacing: 10
    padding: 10, 10
    space_x: self.size[0]/3

    RecycleBoxLayout:
        color: (0, 0.7, 0.4, 0.8)
        default_size: None, dp(56)
        default_size_hint: 0.4, None
        size_hint_y: None
        height: self.minimum_height
        orientation: "vertical"

<ScreenManagement>:
    StartScreen:
        id:page1

    ListyZakupow:
        id:page2

    DodajProdukt:

    MojaLodowa:
        id:page3

    Przepisy:
        id:page4     

    Sniadanie:
        id:page5

    Lunch:
        id:page6

    Obiad:
        id:page7

    Kolacja:
        id:page8



    

<StartScreen>:
    name:'menu'
    
    BoxLayout:
        orientation: 'vertical'

        GridLayout:
            cols: 3
            rows: 1
            size_hint: 1, .1
        
            Button:
                text: 'Listy zakupów'
                on_press: root.manager.current = 'ListyZakupow'

            Button:
                text: 'Moja Lodówa'
                on_press: root.manager.current = 'MojaLodowa'

            Button:
                text: 'Przepisy'
                on_press: root.manager.current = 'Przepisy'

        Image:
            source: 'lodowa.png'
            size_hint: 1, .9


<ListyZakupow>:
    name: 'ListyZakupow'

    BoxLayout:
        orientation:'vertical'

        GridLayout:
            cols: 3
            rows: 1
            size_hint: 1, .1

            Button:
                text: 'Listy zakupów'
                background_color: (0,1,0,1)
                on_press: root.manager.current = 'ListyZakupow'

            Button:
                text: 'Moja Lodówa'
                on_press: root.manager.current = 'MojaLodowa'
            Button:
                text: 'Przepisy'
                on_press: root.manager.current = 'Przepisy'

        RV_Lista:
            size_hint: 1, .8
            id: recycle_view2
        
        GridLayout:
            cols:2
            rows:1
            size_hint: 1, .1
        
            Button:
                text:'Dodaj produkt'
                size_hint: .3, 1
                background_color: (0,1,0,1)
                on_press: root.manager.current = 'DodajProdukt'

            Spinner:
                id: spinner_id
                size_hint: .3, 1
                text:'Kupilem'
                background_color: (0,1,0,1)
                on_press: root.read()
                values: root.shop_list
                on_text: root.kup(spinner_id.text)
                
            

<DodajProdukt>:
    name: 'DodajProdukt'
    textinput: input
    
    BoxLayout:
        orientation: 'vertical'
        size_hint: 0.5, 0.2
        pos: root.center_x - (1/2)*self.width, root.center_y - (1/2)*self.height
        TextInput:
            id: input
            font_size: 24
            multiline: False
            
        BoxLayout:
            orientation: 'horizontal' 
            Button:
                text: 'Dodaj produkt'
                on_press: root.new_score()
            Button:
                text: "Anuluj"
                on_press: root.manager.current = 'ListyZakupow'



<MojaLodowa>:
    name: 'MojaLodowa'

    BoxLayout:
        orientation: 'vertical'
        
        GridLayout:
            cols: 3
            rows: 1
            size_hint: 1, .1

            Button:
                text: 'Listy zakupów'
                on_press: root.manager.current = 'ListyZakupow'

            Button:
                text: 'Moja Lodówa'
                background_color: (0,1,0,1)
                on_press: root.manager.current = 'MojaLodowa'

            Button:
                text: 'Przepisy'
                on_press: root.manager.current = 'Przepisy'

        RV_Lodowa:
            size_hint: 1, .9
                


<Przepisy>:
    name: 'Przepisy'

    BoxLayout:
        orientation: 'vertical'

        GridLayout:
            cols: 3
            rows: 1
            size_hint: 1, .1
        
            Button:
                text: 'Listy zakupów'
                on_press: root.manager.current = 'ListyZakupow'

            Button:
                text: 'Moja Lodówa'
                on_press: root.manager.current = 'MojaLodowa'

            Button:
                text: 'Przepisy'
                background_color: (0,1,0,1)
                on_press: root.manager.current = 'Przepisy'

        Button:
            text: 'Śniadanie'
            size_hint: 1, .225
            background_color: (0,0.8,0,0.8)
            on_press: root.manager.current = 'Sniadanie'

        Button:
            text: 'Lunch'
            size_hint: 1, .225
            background_color: (0,1.1,0,1.1)
            on_press: root.manager.current = 'Lunch'
        
        Button:
            text: 'Obiad'
            size_hint: 1, .225
            background_color: (0,0.8,0,0.8)
            on_press: root.manager.current = 'Obiad'

        Button:
            text: 'Kolacja'
            size_hint: 1, .225
            background_color: (0,1.1,0,1.1)
            on_press: root.manager.current = 'Kolacja'


<Sniadanie>:
    name: 'Sniadanie'

    BoxLayout:
        orientation: 'vertical'

        Button: 
            text: 'Wyjdź'
            size_hint: 1, .1
            on_press: root.manager.current = 'Przepisy'

        RV_Sniadanie:
            size_hint: 1, .9

        


<Lunch>:
    name: 'Lunch'

    BoxLayout:
        orientation: 'vertical'

        Button: 
            text: 'Wyjdź'
            size_hint: 1, .1
            on_press: root.manager.current = 'Przepisy'

        RV_Lunch:
            size_hint: 1, .9


<Obiad>:
    name: 'Obiad'

    BoxLayout:
        orientation: 'vertical'

        Button: 
            text: 'Wyjdź'
            size_hint: 1, .1
            on_press: root.manager.current = 'Przepisy'

        RV_Obiad:
            size_hint: 1, .9



<Kolacja>:
    name: 'Kolacja'

    BoxLayout:
        orientation: 'vertical'

        Button: 
            text: 'Wyjdź'
            size_hint: 1, .1
            on_press: root.manager.current = 'Przepisy' 

        RV_Kolacja:
            size_hint: 1, .9